name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      sqlite:
        image: nouchka/sqlite3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r bookstore/requirements.txt
          pip install pytest pytest-cov
      - name: Run Tests
        run: |
          pytest tests --disable-warnings
